<a href="https://colab.research.google.com/github/beekal/MachieneLearningProjects/blob/master/0%20Basics%20-%20TF/0.%20TF_Review_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TF 1.0 Review Notes

In [0]:
! pip -q install tensorflow==1.14

## TF GPU Check

In [2]:
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  #raise SystemError('GPU device not found')
  print('GPU device not found')
else:
  print('Found GPU at: {}'.format(device_name))

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or 

GPU device not found


## TF Program Exection:

In [3]:
# Session : Env that holds all variables and performs operation. Allocate / deallocates memory within the session
## OPTION 1
import tensorflow as tf
a = tf.add(1,2)
sess = tf.Session()
print('1.' ,sess.run(a))
sess.close()


##  OPTION 2: Inside tf.Session()
with tf.Session() as sess:
  print('2.',sess.run(a))


1. 3
2. 3


## Run Multiple TF Operations

In [4]:
## Multiple variable retrieval
a = tf.add(1,2)
d = tf.subtract(1,2)

with tf.Session() as sess:
  add, subtract = sess.run([a,d])
  print('3.', add, subtract)

3. 3 -1


## Debug TF Program

In [18]:
""" DEBUG with tensorboard """
x = tf.add(2, 3, name="add_debug_sample")

# Add writer after graph definition and before running our session
write = tf.summary.FileWriter('./graphs/1', tf.get_default_graph())
with tf.Session() as sess_g:
	print(sess_g.run(x))
write.close() # close the writer when you’re done using it
write.flush()

"""
Go to terminal, run:
$ python3 [yourprogram].py
$ tensorboard --logdir="./graphs" --port 6006
Then open your browser and go to: http://localhost:6006/
"""
# %load_ext tensorboard
# %tensorboard --logdir ./graphs/1

5


/usr/local/lib/python3.6/dist-packages/tensorflow/python/summary/writer/writer.py:386: UserWarning: Attempting to use a closed FileWriter. The operation will be a noop unless the FileWriter is explicitly reopened.
  warnings.warn("Attempting to use a closed FileWriter. "


'\nGo to terminal, run:\n$ python3 [yourprogram].py\n$ tensorboard --logdir="./graphs" --port 6006\nThen open your browser and go to: http://localhost:6006/\n'

## TF Placeholders


In [6]:
""" Placeholder and feed_dict example """

X = tf.placeholder(tf.float16, shape=(1,) )
b = tf.constant([1], dtype=tf.float16)
y_hat = tf.add(X, b)

with tf.Session() as sess:
  pred = sess.run(y_hat, feed_dict={X: [2]} )
  print('4. y_hat for input x= [2] is ',pred)

4. y_hat for input x= [2] is  [3.]


## TF Arithematic operations

In [7]:
b = tf.constant([ [0, 1],\
                  [2, 3] ], name='b')
a = tf.constant(  [1, 2], name='a') # i.e [ [0/1, 1/2], [2/1, 3/2] ]

with tf.Session() as sess:
    print(sess.run(tf.div(b, a)))       # [ [0,0]   ,  [2,1]]
    print(sess.run(tf.divide(b, a)))    # [ [0.,0.5] ,  [2.,1.5]]
    print(sess.run(tf.truediv(b, a)))   # [ [0.,0.5] ,  [2.,1.5]]
    print(sess.run(tf.floordiv(b, a)))  # [ [0,0] ,  [2,1]]
    # print(sess.run(tf.realdiv(b, a))) 
    print(sess.run(tf.truncatediv(b, a))) # [ [0,0] ,  [2,1]]
    print(sess.run(tf.floor_div(b, a)))   # [ [0,0] ,  [2,1]]


Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
[[0 0]
 [2 1]]
[[0.  0.5]
 [2.  1.5]]
[[0.  0.5]
 [2.  1.5]]
[[0 0]
 [2 1]]
[[0 0]
 [2 1]]
[[0 0]
 [2 1]]


## TF CrossProduct / Dot product operation
1. Cross Product : Cross Product of two vector is always a vector. 
2. Dot Product of a two vector is always a scalar.

In [8]:
a = tf.constant([10, 20], name='a')
b = tf.constant([2, 3], name='b')

with tf.Session() as sess:
    print(sess.run(tf.multiply(a, b)))             # [20, 60]
    print(sess.run(tf.tensordot(a, b, axes=1)))    # = [10 20] [2     = 10*2 +20*3 = 80
                                                   #            3]
    print(sess.run(tf.tensordot(a, b, axes=0)))    # = [ 10   * [2 3]  = [ [20 30]
                                                   #     20 ]              [40 60] ]

[20 60]
80
[[20 30]
 [40 60]]


## TF Zero / One Matrix

In [9]:
z = tf.zeros(5, tf.float16)
z_l = tf.zeros_like( [1,2,3] ) # create zero tensor  with shape equivalent to the given tensor
o = tf.ones(5, tf.float16)

with tf.Session() as sess:
  print(sess.run([z, z_l, o]))
  print(sess.run(o))
  print(sess.run(o) + [2,2,2,2,2])


[array([0., 0., 0., 0., 0.], dtype=float16), array([0, 0, 0], dtype=int32), array([1., 1., 1., 1., 1.], dtype=float16)]
[1. 1. 1. 1. 1.]
[3. 3. 3. 3. 3.]


# TF Data Distributions/ Range/  Shuffle :
1. When initialising the random  weights, always choose truncated_normal because it creates value that is  not more than 2 sdaway from its mean.

In [10]:
#  1 to 100 evenly spaced numbers
nums = tf.lin_space(1.0 ,100.0 ,100,name="1_to_100_evenly_spaced_floats")
ints = tf.range(1,20, 1, name="1_to_20_step_1_ints")

norm = tf.random_normal( shape=[1,10], mean=0.0, stddev=1.0)
norm_trunc = tf.truncated_normal(shape=[1,10], mean=0.0, stddev=1.0) # USED GENERALLY because doesn’t create any values more than two standard deviations away from its mean
unif = tf.random_uniform(shape=[1,5], minval=0, maxval=5)          #
shuf = tf.random_shuffle([[1,1] , [2,1] , [3,1] ])                      # [[1 1] [3 1] [2 1]]
shuf_1d = tf.random_shuffle([1,2,3])                      # [3,2,1]
#tf.random_crop
cat = tf.random.categorical([[0.25, 0.25,0.25,0.25]], 4)   # 4 classes  randomly selected [[0, 0, 2, 3]]
#tf.random_gamma

with tf.Session() as sess:
  print(sess.run(nums) )
  print(sess.run(ints) )
  print(sess.run(norm) )
  print(sess.run(norm_trunc))
  print(sess.run(unif))
  print(sess.run(shuf))
  print(sess.run(shuf_1d))
  print(sess.run(cat))

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[-1.8296789   0.3312855   0.04222503 -0.39106786 -0.07118341 -0.1664562
   0.5545502  -1.3323288   0.4668806   0.5413239 ]]
[[ 1.7089756  -1.0712708  -0.28674734 -1.7274494   0.10814511 -0.736077
   0.655966   -0.34362504  0.19029415  1.0165874 ]]
[[3.9851677  4.0052323  0.9594399  0.09485364 0.91287196]]
[[2 1]
 [3 1]
 [1 1]]
[3 2 1]
[[1 2 0 1]]


## TF Constants : Beware of using them
1.  We should be careful to use the TF constants, because they are  used/ embedded in the graph directly as a part of a graph. Hence if  the constant is larger that 2 GB then it exceeds the Graph limit and hence would generate error. Plus even if you constant is less than 2 GB during the graph computation, they can be copied over multiple times and hence exceed the 2 GB limit due to its multiple use and cause graph computation to fail.

Solution: Instead you can use the constant as a variable to overcome this problem. 

In [0]:
### DO NOT USE CONSTANTS, Because they are used in the graph directly and hence  makes loading graph expensive. USE VARIABLES  instead
const_1 = tf.get_variable(name='constant_1', initializer=tf.constant(2) )

## tf.get_variable vs tf.Variable: Which one to use ?
- Always use tf.get_variable as far as possible because tf.Variable is a class and contains a lot of extra operations , hence more overhead and more memory and other resource consumption. Hence use tf.get_variables wherever possible

In [12]:
""" Variable examples : tf.Variable(2, name='scalar')  VS tf.get_variable('scalar', initializer=tf.constant(2))
    Use tf.get_variable because tf.Variable is a class with  lot of  extra operations which  then consumes more memory
"""
const = tf.get_variable(name='constant', initializer=tf.constant(2) )
weights = tf.get_variable(name="weights", shape=(2, 5), initializer=tf.truncated_normal_initializer(mean=0.0, stddev=1.0))

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  print(weights.eval())
  print('')



[[ 0.4095752  -0.69069004 -0.8436467  -0.24726255 -0.891231  ]
 [ 0.9511935   0.12729074 -0.88585967  1.0111473  -0.18794669]]



## TF variable : Reassign value

In [13]:
a = tf.get_variable('a_1', initializer=tf.constant(2) )
a_times_two = a.assign(a * 2)

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  print(sess.run(a))   # >> 4 
  print(sess.run(a_times_two ))   # >> 4 
  print(sess.run(a_times_two ))   # >> 8
  print(sess.run(a_times_two ))   # >> 16


# Add / Reassign variables from within scope
a = tf.get_variable('a_3', initializer=tf.constant(2) )
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(a))   # >> 4 
    print(sess.run(a.assign_add(2)) )   # >> 4 
    print(sess.run(a.assign_sub(2) ))   # >> 2
    

2
4
8
16
2
4
2


## TF Variable Scoping @ Session

In [14]:
## Variable : Each session has its own copy

a = tf.get_variable('a_4', initializer=tf.constant(2))

sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(tf.global_variables_initializer())
sess2.run(tf.global_variables_initializer())

print('SESSION 1: Adding 20 to a', sess1.run(a.assign_add(20))) # >> 22
print('SESSION 2: Adding 2 to a',sess2.run(a.assign_add(2))) # >> 4

print('SESSION 1: Adding 20 to a', sess1.run(a.assign_add(20))) # >> 42
print('SESSION 2: Adding 2 to a',sess2.run(a.assign_add(2))) # >> 6

sess1.close()
sess2.close()

SESSION 1: Adding 20 to a 22
SESSION 2: Adding 2 to a 4
SESSION 1: Adding 20 to a 42
SESSION 2: Adding 2 to a 6


## TF Weight variable

In [0]:
# W =tf.get_variable('weights1',  tf.truncated_normal( [700, 10] )  )


## TF Normal Loading vs Lazy Loading  : 1 Add node vs 10 Add nodes created

In [0]:
######################################## 
## NORMAL LOADING   			      ##
## print out a graph with 1 Add node  ## 
########################################

x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
z = tf.add(x, y)

with tf.Session() as sess:
	sess.run(tf.global_variables_initializer())
	writer = tf.summary.FileWriter('graphs/normal_loading', sess.graph)
	for _ in range(3):
		sess.run(z)
	# print(tf.get_default_graph().as_graph_def())
	writer.close()

######################################## 
## LAZY LOADING   					  ##
## print out a graph with 10 Add nodes## 
########################################

x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')

with tf.Session() as sess:
	sess.run(tf.global_variables_initializer())
	writer = tf.summary.FileWriter('graphs/lazy_loading', sess.graph)
	for _ in range(3):
		sess.run(tf.add(x, y))
	# print(tf.get_default_graph().as_graph_def()) 
	writer.close()